CREATE TABLE "PROPERTIES" (
    "APPLICATION" VARCHAR(128),
    "PROFILE" VARCHAR(128),
    "LABEL" VARCHAR(128),
    "KEY" VARCHAR(256),
    "VALUE" VARCHAR(4096),
    PRIMARY KEY ("APPLICATION", "PROFILE", "LABEL", "KEY")
);